//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects.Generator.Core.Localizacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Objects.Generator.Core.Localizacion.ExceptionsMessages", typeof(ExceptionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufix not provided (ClassMetadata section).
        /// </summary>
        public static string MsgClassMetadataSufixNotProvided {
            get {
                return ResourceManager.GetString("MsgClassMetadataSufixNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not active connection (Connection section).
        /// </summary>
        public static string MsgConnectionNotActive {
            get {
                return ResourceManager.GetString("MsgConnectionNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectionstring not provided (Connection section).
        /// </summary>
        public static string MsgConnectionStringNotProvided {
            get {
                return ResourceManager.GetString("MsgConnectionStringNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not provided (Connection section).
        /// </summary>
        public static string MsgDatabaseNotProvided {
            get {
                return ResourceManager.GetString("MsgDatabaseNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languaje not provided (Namespaces section).
        /// </summary>
        public static string MsgLanguajeNotProvided {
            get {
                return ResourceManager.GetString("MsgLanguajeNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not provided (MetadataAttribute section).
        /// </summary>
        public static string MsgMetadataNameNotProvided {
            get {
                return ResourceManager.GetString("MsgMetadataNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not provided (MetadataAttribute section).
        /// </summary>
        public static string MsgMetadataTypeNotProvided {
            get {
                return ResourceManager.GetString("MsgMetadataTypeNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace destiny path not provided (Namespace section).
        /// </summary>
        public static string MsgNamespaceDestinyNotProvided {
            get {
                return ResourceManager.GetString("MsgNamespaceDestinyNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace name not provided (Namespace section).
        /// </summary>
        public static string MsgNamespaceNotProvider {
            get {
                return ResourceManager.GetString("MsgNamespaceNotProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace type not provided (Namespace section).
        /// </summary>
        public static string MsgNamespaceTypeNotProvider {
            get {
                return ResourceManager.GetString("MsgNamespaceTypeNotProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider not provided (Connection section).
        /// </summary>
        public static string MsgProviderNotProvided {
            get {
                return ResourceManager.GetString("MsgProviderNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in configuration section..
        /// </summary>
        public static string MsgSectionNotCorrect {
            get {
                return ResourceManager.GetString("MsgSectionNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not provided (Connection section).
        /// </summary>
        public static string MsgServerNotProvided {
            get {
                return ResourceManager.GetString("MsgServerNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout not provided (Connection section).
        /// </summary>
        public static string MsgTimeoutNotProvided {
            get {
                return ResourceManager.GetString("MsgTimeoutNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using not provided (Import section).
        /// </summary>
        public static string MsgUsingNotProvided {
            get {
                return ResourceManager.GetString("MsgUsingNotProvided", resourceCulture);
            }
        }
    }
}
