//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



public sealed class GeneratorObjects {
    
    private static GeneratorObjectsSection _config;
    
    static GeneratorObjects() {
        _config = ((GeneratorObjectsSection)(global::System.Configuration.ConfigurationManager.GetSection("GeneratorObjects")));
    }
    
    private GeneratorObjects() {
    }
    
    public static GeneratorObjectsSection Config {
        get {
            return _config;
        }
    }
}

public sealed partial class GeneratorObjectsSection : System.Configuration.ConfigurationSection {
    
    [System.Configuration.ConfigurationPropertyAttribute("GeneratorConnections")]
    [System.Configuration.ConfigurationCollectionAttribute(typeof(GeneratorConnectionsElementCollection.GeneratorConnectionElement), AddItemName="GeneratorConnection")]
    public GeneratorConnectionsElementCollection GeneratorConnections {
        get {
            return ((GeneratorConnectionsElementCollection)(this["GeneratorConnections"]));
        }
    }
    
    [System.Configuration.ConfigurationPropertyAttribute("NameSpaces")]
    [System.Configuration.ConfigurationCollectionAttribute(typeof(NameSpacesElementCollection.NamespaceElement), AddItemName="Namespace")]
    public NameSpacesElementCollection NameSpaces {
        get {
            return ((NameSpacesElementCollection)(this["NameSpaces"]));
        }
    }
    
    public sealed partial class GeneratorConnectionsElementCollection : System.Configuration.ConfigurationElementCollection {
        
        public GeneratorConnectionElement this[int i] {
            get {
                return ((GeneratorConnectionElement)(this.BaseGet(i)));
            }
        }
        
        protected override System.Configuration.ConfigurationElement CreateNewElement() {
            return new GeneratorConnectionElement();
        }
        
        protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
            return ((GeneratorConnectionElement)(element)).Id;
        }
        
        public sealed partial class GeneratorConnectionElement : System.Configuration.ConfigurationElement {
            
            [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
            public long Id {
                get {
                    return ((long)(this["id"]));
                }
                set {
                    this["id"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("enabled", IsRequired=true)]
            public bool Enabled {
                get {
                    return ((bool)(this["enabled"]));
                }
                set {
                    this["enabled"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("provider", IsRequired=true)]
            public string Provider {
                get {
                    return ((string)(this["provider"]));
                }
                set {
                    this["provider"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("ConectionChain")]
            public ConectionChainElement ConectionChain {
                get {
                    return ((ConectionChainElement)(this["ConectionChain"]));
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("ConnectionOptions")]
            public ConnectionOptionsElement ConnectionOptions {
                get {
                    return ((ConnectionOptionsElement)(this["ConnectionOptions"]));
                }
            }
            
            public sealed partial class ConectionChainElement : System.Configuration.ConfigurationElement {
                
                [System.Configuration.ConfigurationPropertyAttribute("connectionString", IsRequired=true)]
                public string ConnectionString {
                    get {
                        return ((string)(this["connectionString"]));
                    }
                    set {
                        this["connectionString"] = value;
                    }
                }
            }
            
            public sealed partial class ConnectionOptionsElement : System.Configuration.ConfigurationElement {
                
                [System.Configuration.ConfigurationPropertyAttribute("server", IsRequired=true)]
                public string Server {
                    get {
                        return ((string)(this["server"]));
                    }
                    set {
                        this["server"] = value;
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("database", IsRequired=true)]
                public string Database {
                    get {
                        return ((string)(this["database"]));
                    }
                    set {
                        this["database"] = value;
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("user", IsRequired=true)]
                public string User {
                    get {
                        return ((string)(this["user"]));
                    }
                    set {
                        this["user"] = value;
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("password", IsRequired=true)]
                public string Password {
                    get {
                        return ((string)(this["password"]));
                    }
                    set {
                        this["password"] = value;
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("timeout", IsRequired=true)]
                public long Timeout {
                    get {
                        return ((long)(this["timeout"]));
                    }
                    set {
                        this["timeout"] = value;
                    }
                }
            }
        }
    }
    
    public sealed partial class NameSpacesElementCollection : System.Configuration.ConfigurationElementCollection {
        
        [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
        public string Name {
            get {
                return ((string)(this["name"]));
            }
            set {
                this["name"] = value;
            }
        }
        
        [System.Configuration.ConfigurationPropertyAttribute("languaje", IsRequired=true)]
        public long Languaje {
            get {
                return ((long)(this["languaje"]));
            }
            set {
                this["languaje"] = value;
            }
        }
        
        public NamespaceElement this[int i] {
            get {
                return ((NamespaceElement)(this.BaseGet(i)));
            }
        }
        
        protected override System.Configuration.ConfigurationElement CreateNewElement() {
            return new NamespaceElement();
        }
        
        protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
            return ((NamespaceElement)(element)).Id;
        }
        
        public sealed partial class NamespaceElement : System.Configuration.ConfigurationElement {
            
            [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
            public long Id {
                get {
                    return ((long)(this["id"]));
                }
                set {
                    this["id"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
            public string Name {
                get {
                    return ((string)(this["name"]));
                }
                set {
                    this["name"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("type", IsRequired=true)]
            public string Type {
                get {
                    return ((string)(this["type"]));
                }
                set {
                    this["type"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("destinyPath", IsRequired=true)]
            public string DestinyPath {
                get {
                    return ((string)(this["destinyPath"]));
                }
                set {
                    this["destinyPath"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("enabled", IsRequired=true)]
            public bool Enabled {
                get {
                    return ((bool)(this["enabled"]));
                }
                set {
                    this["enabled"] = value;
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("GeneratorOptions")]
            public GeneratorOptionsElement GeneratorOptions {
                get {
                    return ((GeneratorOptionsElement)(this["GeneratorOptions"]));
                }
            }
            
            [System.Configuration.ConfigurationPropertyAttribute("Imports")]
            [System.Configuration.ConfigurationCollectionAttribute(typeof(ImportsElementCollection.ImportElement), AddItemName="Import")]
            public ImportsElementCollection Imports {
                get {
                    return ((ImportsElementCollection)(this["Imports"]));
                }
            }
            
            public sealed partial class GeneratorOptionsElement : System.Configuration.ConfigurationElement {
                
                [System.Configuration.ConfigurationPropertyAttribute("blankLinesBetweenMembers", IsRequired=true)]
                public bool BlankLinesBetweenMembers {
                    get {
                        return ((bool)(this["blankLinesBetweenMembers"]));
                    }
                    set {
                        this["blankLinesBetweenMembers"] = value;
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("ClassEntity")]
                public ClassEntityElement ClassEntity {
                    get {
                        return ((ClassEntityElement)(this["ClassEntity"]));
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("PrivateProperties")]
                public PrivatePropertiesElement PrivateProperties {
                    get {
                        return ((PrivatePropertiesElement)(this["PrivateProperties"]));
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("PublicProperties")]
                public PublicPropertiesElement PublicProperties {
                    get {
                        return ((PublicPropertiesElement)(this["PublicProperties"]));
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("PublicMethods")]
                [System.Configuration.ConfigurationCollectionAttribute(typeof(PublicMethodsElementCollection.PublicMethodElement), AddItemName="PublicMethod")]
                public PublicMethodsElementCollection PublicMethods {
                    get {
                        return ((PublicMethodsElementCollection)(this["PublicMethods"]));
                    }
                }
                
                [System.Configuration.ConfigurationPropertyAttribute("PrivateMethods")]
                [System.Configuration.ConfigurationCollectionAttribute(typeof(PrivateMethodsElementCollection.PrivateMethodElement), AddItemName="PrivateMethod")]
                public PrivateMethodsElementCollection PrivateMethods {
                    get {
                        return ((PrivateMethodsElementCollection)(this["PrivateMethods"]));
                    }
                }
                
                public sealed partial class ClassEntityElement : System.Configuration.ConfigurationElement {
                    
                    [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                    public long Id {
                        get {
                            return ((long)(this["id"]));
                        }
                        set {
                            this["id"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("partial", IsRequired=true)]
                    public bool Partial {
                        get {
                            return ((bool)(this["partial"]));
                        }
                        set {
                            this["partial"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("sealed", IsRequired=true)]
                    public bool Sealed {
                        get {
                            return ((bool)(this["sealed"]));
                        }
                        set {
                            this["sealed"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("isEnum", IsRequired=true)]
                    public bool IsEnum {
                        get {
                            return ((bool)(this["isEnum"]));
                        }
                        set {
                            this["isEnum"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("fieldsEnum", IsRequired=true)]
                    public bool FieldsEnum {
                        get {
                            return ((bool)(this["fieldsEnum"]));
                        }
                        set {
                            this["fieldsEnum"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("withMetadata", IsRequired=true)]
                    public bool WithMetadata {
                        get {
                            return ((bool)(this["withMetadata"]));
                        }
                        set {
                            this["withMetadata"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("addConstructorWithParameters", IsRequired=true)]
                    public bool AddConstructorWithParameters {
                        get {
                            return ((bool)(this["addConstructorWithParameters"]));
                        }
                        set {
                            this["addConstructorWithParameters"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("Constructor")]
                    public ConstructorElement Constructor {
                        get {
                            return ((ConstructorElement)(this["Constructor"]));
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("ClassMetadata")]
                    public ClassMetadataElement ClassMetadata {
                        get {
                            return ((ClassMetadataElement)(this["ClassMetadata"]));
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("Enumerations")]
                    public EnumerationsElement Enumerations {
                        get {
                            return ((EnumerationsElement)(this["Enumerations"]));
                        }
                    }
                    
                    public sealed partial class ConstructorElement : System.Configuration.ConfigurationElement {
                        
                        [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                        public long Id {
                            get {
                                return ((long)(this["id"]));
                            }
                            set {
                                this["id"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("startRegion", IsRequired=true)]
                        public string StartRegion {
                            get {
                                return ((string)(this["startRegion"]));
                            }
                            set {
                                this["startRegion"] = value;
                            }
                        }
                    }
                    
                    public sealed partial class ClassMetadataElement : System.Configuration.ConfigurationElement {
                        
                        [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                        public long Id {
                            get {
                                return ((long)(this["id"]));
                            }
                            set {
                                this["id"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("sufix", IsRequired=true)]
                        public string Sufix {
                            get {
                                return ((string)(this["sufix"]));
                            }
                            set {
                                this["sufix"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("Attributes")]
                        [System.Configuration.ConfigurationCollectionAttribute(typeof(AttributesElementCollection.AttributeElement), AddItemName="Attribute")]
                        public AttributesElementCollection Attributes {
                            get {
                                return ((AttributesElementCollection)(this["Attributes"]));
                            }
                        }
                        
                        public sealed partial class AttributesElementCollection : System.Configuration.ConfigurationElementCollection {
                            
                            public AttributeElement this[int i] {
                                get {
                                    return ((AttributeElement)(this.BaseGet(i)));
                                }
                            }
                            
                            protected override System.Configuration.ConfigurationElement CreateNewElement() {
                                return new AttributeElement();
                            }
                            
                            protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                                return ((AttributeElement)(element)).Id;
                            }
                            
                            public sealed partial class AttributeElement : System.Configuration.ConfigurationElement {
                                
                                [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                                public long Id {
                                    get {
                                        return ((long)(this["id"]));
                                    }
                                    set {
                                        this["id"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("type", IsRequired=true)]
                                public string Type {
                                    get {
                                        return ((string)(this["type"]));
                                    }
                                    set {
                                        this["type"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                                public string Name {
                                    get {
                                        return ((string)(this["name"]));
                                    }
                                    set {
                                        this["name"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("value", IsRequired=true)]
                                public string Value {
                                    get {
                                        return ((string)(this["value"]));
                                    }
                                    set {
                                        this["value"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("messageProperty", IsRequired=true)]
                                public string MessageProperty {
                                    get {
                                        return ((string)(this["messageProperty"]));
                                    }
                                    set {
                                        this["messageProperty"] = value;
                                    }
                                }
                            }
                        }
                    }
                    
                    public sealed partial class EnumerationsElement : System.Configuration.ConfigurationElement {
                        
                        [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                        public long Id {
                            get {
                                return ((long)(this["id"]));
                            }
                            set {
                                this["id"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("enumAttribute", IsRequired=true)]
                        public string EnumAttribute {
                            get {
                                return ((string)(this["enumAttribute"]));
                            }
                            set {
                                this["enumAttribute"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("endEnums", IsRequired=true)]
                        public string EndEnums {
                            get {
                                return ((string)(this["endEnums"]));
                            }
                            set {
                                this["endEnums"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("addAttribute", IsRequired=true)]
                        public bool AddAttribute {
                            get {
                                return ((bool)(this["addAttribute"]));
                            }
                            set {
                                this["addAttribute"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("message", IsRequired=true)]
                        public string Message {
                            get {
                                return ((string)(this["message"]));
                            }
                            set {
                                this["message"] = value;
                            }
                        }
                    }
                }
                
                public sealed partial class PrivatePropertiesElement : System.Configuration.ConfigurationElement {
                    
                    [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                    public long Id {
                        get {
                            return ((long)(this["id"]));
                        }
                        set {
                            this["id"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("startRegion", IsRequired=true)]
                    public string StartRegion {
                        get {
                            return ((string)(this["startRegion"]));
                        }
                        set {
                            this["startRegion"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("endRegion", IsRequired=true)]
                    public string EndRegion {
                        get {
                            return ((string)(this["endRegion"]));
                        }
                        set {
                            this["endRegion"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("prefixPrivateFields", IsRequired=true)]
                    public string PrefixPrivateFields {
                        get {
                            return ((string)(this["prefixPrivateFields"]));
                        }
                        set {
                            this["prefixPrivateFields"] = value;
                        }
                    }
                }
                
                public sealed partial class PublicPropertiesElement : System.Configuration.ConfigurationElement {
                    
                    [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                    public long Id {
                        get {
                            return ((long)(this["id"]));
                        }
                        set {
                            this["id"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("startRegion", IsRequired=true)]
                    public string StartRegion {
                        get {
                            return ((string)(this["startRegion"]));
                        }
                        set {
                            this["startRegion"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("endRegion", IsRequired=true)]
                    public string EndRegion {
                        get {
                            return ((string)(this["endRegion"]));
                        }
                        set {
                            this["endRegion"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("hasGet", IsRequired=true)]
                    public bool HasGet {
                        get {
                            return ((bool)(this["hasGet"]));
                        }
                        set {
                            this["hasGet"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("hasSet", IsRequired=true)]
                    public bool HasSet {
                        get {
                            return ((bool)(this["hasSet"]));
                        }
                        set {
                            this["hasSet"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("Attributes")]
                    [System.Configuration.ConfigurationCollectionAttribute(typeof(AttributesElementCollection.AttributeElement), AddItemName="Attribute")]
                    public AttributesElementCollection Attributes {
                        get {
                            return ((AttributesElementCollection)(this["Attributes"]));
                        }
                    }
                    
                    public sealed partial class AttributesElementCollection : System.Configuration.ConfigurationElementCollection {
                        
                        public AttributeElement this[int i] {
                            get {
                                return ((AttributeElement)(this.BaseGet(i)));
                            }
                        }
                        
                        protected override System.Configuration.ConfigurationElement CreateNewElement() {
                            return new AttributeElement();
                        }
                        
                        protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                            return ((AttributeElement)(element)).Id;
                        }
                        
                        public sealed partial class AttributeElement : System.Configuration.ConfigurationElement {
                            
                            [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                            public long Id {
                                get {
                                    return ((long)(this["id"]));
                                }
                                set {
                                    this["id"] = value;
                                }
                            }
                            
                            [System.Configuration.ConfigurationPropertyAttribute("type", IsRequired=true)]
                            public string Type {
                                get {
                                    return ((string)(this["type"]));
                                }
                                set {
                                    this["type"] = value;
                                }
                            }
                            
                            [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                            public string Name {
                                get {
                                    return ((string)(this["name"]));
                                }
                                set {
                                    this["name"] = value;
                                }
                            }
                            
                            [System.Configuration.ConfigurationPropertyAttribute("value", IsRequired=true)]
                            public string Value {
                                get {
                                    return ((string)(this["value"]));
                                }
                                set {
                                    this["value"] = value;
                                }
                            }
                            
                            [System.Configuration.ConfigurationPropertyAttribute("messageProperty", IsRequired=true)]
                            public string MessageProperty {
                                get {
                                    return ((string)(this["messageProperty"]));
                                }
                                set {
                                    this["messageProperty"] = value;
                                }
                            }
                        }
                    }
                }
                
                public sealed partial class PublicMethodsElementCollection : System.Configuration.ConfigurationElementCollection {
                    
                    public PublicMethodElement this[int i] {
                        get {
                            return ((PublicMethodElement)(this.BaseGet(i)));
                        }
                    }
                    
                    protected override System.Configuration.ConfigurationElement CreateNewElement() {
                        return new PublicMethodElement();
                    }
                    
                    protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                        return ((PublicMethodElement)(element)).Id;
                    }
                    
                    public sealed partial class PublicMethodElement : System.Configuration.ConfigurationElement {
                        
                        [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                        public long Id {
                            get {
                                return ((long)(this["id"]));
                            }
                            set {
                                this["id"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                        public string Name {
                            get {
                                return ((string)(this["name"]));
                            }
                            set {
                                this["name"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("returnType", IsRequired=true)]
                        public string ReturnType {
                            get {
                                return ((string)(this["returnType"]));
                            }
                            set {
                                this["returnType"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("ExceptionMethod")]
                        public ExceptionMethodElement ExceptionMethod {
                            get {
                                return ((ExceptionMethodElement)(this["ExceptionMethod"]));
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("Parameters")]
                        [System.Configuration.ConfigurationCollectionAttribute(typeof(ParametersElementCollection.ParameterElement), AddItemName="Parameter")]
                        public ParametersElementCollection Parameters {
                            get {
                                return ((ParametersElementCollection)(this["Parameters"]));
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("Statements")]
                        [System.Configuration.ConfigurationCollectionAttribute(typeof(StatementsElementCollection.StatementElement), AddItemName="Statement")]
                        public StatementsElementCollection Statements {
                            get {
                                return ((StatementsElementCollection)(this["Statements"]));
                            }
                        }
                        
                        public sealed partial class ExceptionMethodElement : System.Configuration.ConfigurationElement {
                            
                            [System.Configuration.ConfigurationPropertyAttribute("typeException", IsRequired=true)]
                            public string TypeException {
                                get {
                                    return ((string)(this["typeException"]));
                                }
                                set {
                                    this["typeException"] = value;
                                }
                            }
                            
                            [System.Configuration.ConfigurationPropertyAttribute("message", IsRequired=true)]
                            public string Message {
                                get {
                                    return ((string)(this["message"]));
                                }
                                set {
                                    this["message"] = value;
                                }
                            }
                        }
                        
                        public sealed partial class ParametersElementCollection : System.Configuration.ConfigurationElementCollection {
                            
                            public ParameterElement this[int i] {
                                get {
                                    return ((ParameterElement)(this.BaseGet(i)));
                                }
                            }
                            
                            protected override System.Configuration.ConfigurationElement CreateNewElement() {
                                return new ParameterElement();
                            }
                            
                            protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                                return ((ParameterElement)(element)).Id;
                            }
                            
                            public sealed partial class ParameterElement : System.Configuration.ConfigurationElement {
                                
                                [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                                public long Id {
                                    get {
                                        return ((long)(this["id"]));
                                    }
                                    set {
                                        this["id"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                                public string Name {
                                    get {
                                        return ((string)(this["name"]));
                                    }
                                    set {
                                        this["name"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("type", IsRequired=true)]
                                public string Type {
                                    get {
                                        return ((string)(this["type"]));
                                    }
                                    set {
                                        this["type"] = value;
                                    }
                                }
                            }
                        }
                        
                        public sealed partial class StatementsElementCollection : System.Configuration.ConfigurationElementCollection {
                            
                            public StatementElement this[int i] {
                                get {
                                    return ((StatementElement)(this.BaseGet(i)));
                                }
                            }
                            
                            protected override System.Configuration.ConfigurationElement CreateNewElement() {
                                return new StatementElement();
                            }
                            
                            protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                                return ((StatementElement)(element)).Id;
                            }
                            
                            public sealed partial class StatementElement : System.Configuration.ConfigurationElement {
                                
                                [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                                public long Id {
                                    get {
                                        return ((long)(this["id"]));
                                    }
                                    set {
                                        this["id"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                                public string Name {
                                    get {
                                        return ((string)(this["name"]));
                                    }
                                    set {
                                        this["name"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("comment", IsRequired=true)]
                                public string Comment {
                                    get {
                                        return ((string)(this["comment"]));
                                    }
                                    set {
                                        this["comment"] = value;
                                    }
                                }
                            }
                        }
                    }
                }
                
                public sealed partial class PrivateMethodsElementCollection : System.Configuration.ConfigurationElementCollection {
                    
                    public PrivateMethodElement this[int i] {
                        get {
                            return ((PrivateMethodElement)(this.BaseGet(i)));
                        }
                    }
                    
                    protected override System.Configuration.ConfigurationElement CreateNewElement() {
                        return new PrivateMethodElement();
                    }
                    
                    protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                        return ((PrivateMethodElement)(element)).Id;
                    }
                    
                    public sealed partial class PrivateMethodElement : System.Configuration.ConfigurationElement {
                        
                        [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                        public long Id {
                            get {
                                return ((long)(this["id"]));
                            }
                            set {
                                this["id"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                        public string Name {
                            get {
                                return ((string)(this["name"]));
                            }
                            set {
                                this["name"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("returnType", IsRequired=true)]
                        public string ReturnType {
                            get {
                                return ((string)(this["returnType"]));
                            }
                            set {
                                this["returnType"] = value;
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("ExceptionMethod")]
                        public ExceptionMethodElement ExceptionMethod {
                            get {
                                return ((ExceptionMethodElement)(this["ExceptionMethod"]));
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("Parameters")]
                        [System.Configuration.ConfigurationCollectionAttribute(typeof(ParametersElementCollection.ParameterElement), AddItemName="Parameter")]
                        public ParametersElementCollection Parameters {
                            get {
                                return ((ParametersElementCollection)(this["Parameters"]));
                            }
                        }
                        
                        [System.Configuration.ConfigurationPropertyAttribute("Statements")]
                        [System.Configuration.ConfigurationCollectionAttribute(typeof(StatementsElementCollection.StatementElement), AddItemName="Statement")]
                        public StatementsElementCollection Statements {
                            get {
                                return ((StatementsElementCollection)(this["Statements"]));
                            }
                        }
                        
                        public sealed partial class ExceptionMethodElement : System.Configuration.ConfigurationElement {
                            
                            [System.Configuration.ConfigurationPropertyAttribute("typeException", IsRequired=true)]
                            public string TypeException {
                                get {
                                    return ((string)(this["typeException"]));
                                }
                                set {
                                    this["typeException"] = value;
                                }
                            }
                            
                            [System.Configuration.ConfigurationPropertyAttribute("message", IsRequired=true)]
                            public string Message {
                                get {
                                    return ((string)(this["message"]));
                                }
                                set {
                                    this["message"] = value;
                                }
                            }
                        }
                        
                        public sealed partial class ParametersElementCollection : System.Configuration.ConfigurationElementCollection {
                            
                            public ParameterElement this[int i] {
                                get {
                                    return ((ParameterElement)(this.BaseGet(i)));
                                }
                            }
                            
                            protected override System.Configuration.ConfigurationElement CreateNewElement() {
                                return new ParameterElement();
                            }
                            
                            protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                                return ((ParameterElement)(element)).Id;
                            }
                            
                            public sealed partial class ParameterElement : System.Configuration.ConfigurationElement {
                                
                                [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                                public long Id {
                                    get {
                                        return ((long)(this["id"]));
                                    }
                                    set {
                                        this["id"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                                public string Name {
                                    get {
                                        return ((string)(this["name"]));
                                    }
                                    set {
                                        this["name"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("type", IsRequired=true)]
                                public string Type {
                                    get {
                                        return ((string)(this["type"]));
                                    }
                                    set {
                                        this["type"] = value;
                                    }
                                }
                            }
                        }
                        
                        public sealed partial class StatementsElementCollection : System.Configuration.ConfigurationElementCollection {
                            
                            public StatementElement this[int i] {
                                get {
                                    return ((StatementElement)(this.BaseGet(i)));
                                }
                            }
                            
                            protected override System.Configuration.ConfigurationElement CreateNewElement() {
                                return new StatementElement();
                            }
                            
                            protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                                return ((StatementElement)(element)).Id;
                            }
                            
                            public sealed partial class StatementElement : System.Configuration.ConfigurationElement {
                                
                                [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                                public long Id {
                                    get {
                                        return ((long)(this["id"]));
                                    }
                                    set {
                                        this["id"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                                public string Name {
                                    get {
                                        return ((string)(this["name"]));
                                    }
                                    set {
                                        this["name"] = value;
                                    }
                                }
                                
                                [System.Configuration.ConfigurationPropertyAttribute("comment", IsRequired=true)]
                                public string Comment {
                                    get {
                                        return ((string)(this["comment"]));
                                    }
                                    set {
                                        this["comment"] = value;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            public sealed partial class ImportsElementCollection : System.Configuration.ConfigurationElementCollection {
                
                public ImportElement this[int i] {
                    get {
                        return ((ImportElement)(this.BaseGet(i)));
                    }
                }
                
                protected override System.Configuration.ConfigurationElement CreateNewElement() {
                    return new ImportElement();
                }
                
                protected override object GetElementKey(System.Configuration.ConfigurationElement element) {
                    return ((ImportElement)(element)).Id;
                }
                
                public sealed partial class ImportElement : System.Configuration.ConfigurationElement {
                    
                    [System.Configuration.ConfigurationPropertyAttribute("id", IsRequired=true)]
                    public long Id {
                        get {
                            return ((long)(this["id"]));
                        }
                        set {
                            this["id"] = value;
                        }
                    }
                    
                    [System.Configuration.ConfigurationPropertyAttribute("name", IsRequired=true)]
                    public string Name {
                        get {
                            return ((string)(this["name"]));
                        }
                        set {
                            this["name"] = value;
                        }
                    }
                }
            }
        }
    }
}
